### ISSUE TITLE
Add rubocop config?

### ISSUE THREAD

**Issue by horgh** [maxmind/minfraud-api-ruby#22]
Hi!

Would you be open to having a rubocop config in the repo and having rubocop run as part of Travis? I was thinking it could be helpful in terms of getting everything formatted consistently and more automatically. I find it's great when I can run a formatter when making changes to help catch mistakes and also be able to think about that type of thing less.

I'd be happy to give creating one a shot. I'm guessing rubocop will want a bunch of things to be reformatted to satisfy it though, so it might take some discussion to get things in a way that'll fit the project!

**Comment by kushniryb** [comment]
Hey hey! 

Yup, that'd be great 👍  
I'd start with something like this off the top of my head, lemme know what you think! 
```
# == Metrics == #
Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 10

Metrics/ClassLength:
  Max: 100

Metrics/ModuleLength:
  Max: 100

Metrics/ParameterLists:
  Max: 5

# == Layout == #
Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle:      table

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/ExtraSpacing:
  ForceEqualSignAlignment: true

Layout/Tab:
  IndentationWidth: 2

# == Style == #
Style/SymbolArray:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/CollectionMethods:
  Enabled: true

Style/NumericLiterals:
  MinDigits: 4

Style/StringLiterals:
  EnforcedStyle: single_quotes
```
